### ISSUE TITLE
seed.sql file

### ISSUE THREAD

**Issue by MahdiAbbasi7** [meghiaws/storefront#4]
Hi, can you send me seed.sql file??
I would like to practice with some queries in DataGrip, but I do not have access to this file.

**Comment by meghiaws** [comment]
Hi,

Sure, here it is.

**Comment by MahdiAbbasi7** [comment]
How I can download this file? Is it correct link??

**Comment by meghiaws** [comment]
Its attached to previous mail

**Comment by MahdiAbbasi7** [comment]
The link is broken.
